module.exports = {
    botName: "𝐆𝐈𝐅𝐓-𝐀𝐗𝐈𝐒 𝐌𝐃",
    ownerName: "Gift",
    ownerNumber: [(process.env.OWNER_NUMBER || "2347084362145") + "@s.whatsapp.net"],
    pairingNumber: "",
    prefix: ".",
    geminiKey:   process.env.GEMINI_KEY   || "",
    geminiModel: "gemini-2.0-flash",
    telegramBotToken:  process.env.TELEGRAM_BOT_TOKEN  || "",
    telegramBotToken2: process.env.TELEGRAM_BOT_TOKEN2 || "",
    telegramBotToken3: "",
    telegramBotToken4: "",
    telegramBotToken5: "",
    telegramOwnerId:   process.env.TELEGRAM_OWNER_ID   || "",
    ngrokAuthToken: process.env.NGROK_AUTH_TOKEN || "",
    ngrokEnabled:   process.env.NGROK_ENABLED !== "false",
    openPairing: true,
    apiSecretKey: process.env.API_SECRET_KEY || "giftaxis-secret-change-me",
    adminUser:     process.env.ADMIN_USER     || "admin",
    adminPassword: process.env.ADMIN_PASSWORD || "giftaxis123",
    footer: "\n\n> ᴘᴏᴡᴇʀᴇᴅ ʙʏ Gift Axis Labs™",
    autoRead:   false,
    autoStatus: true,
    msg: {
        wait:  "┌ ❏ ◆ ⌜⏳ 𝗣𝗥𝗢𝗖𝗘𝗦𝗦𝗜𝗡𝗚⌟ ◆\n│\n├◆ ᴘʟᴇᴀsᴇ ᴡᴀɪᴛ...\n│\n└ ❏",
        admin: "┌ ❏ ◆ ⌜⚠️ 𝗔𝗗𝗠𝗜𝗡 𝗢𝗡𝗟𝗬⌟ ◆\n│\n├◆ ᴛʜɪs ᴄᴏᴍᴍᴀɴᴅ ʀᴇǫᴜɪʀᴇs ᴀᴅᴍɪɴ\n│\n└ ❏",
        owner: "┌ ❏ ◆ ⌜⚠️ 𝗢𝗪𝗡𝗘𝗥 𝗢𝗡𝗟𝗬⌟ ◆\n│\n├◆ ᴛʜɪs ᴄᴏᴍᴍᴀɴᴅ ʀᴇǫᴜɪʀᴇs ᴏᴡɴᴇʀ\n│\n└ ❏",
        group: "┌ ❏ ◆ ⌜⚠️ 𝗚𝗥𝗢𝗨𝗣 𝗢𝗡𝗟𝗬⌟ ◆\n│\n├◆ ᴜsᴇ ɪɴ ɢʀᴏᴜᴘ ᴄʜᴀᴛ ᴏɴʟʏ\n│\n└ ❏",
        error: "┌ ❏ ◆ ⌜❌ 𝗘𝗥𝗥𝗢𝗥⌟ ◆\n│\n├◆ ᴀɴ ᴇʀʀᴏʀ ᴏᴄᴄᴜʀʀᴇᴅ\n│\n└ ❏"
    }
};module.exports = {
    botName: "𝐆𝐈𝐅𝐓-𝐀𝐗𝐈𝐒 𝐌𝐃",
    ownerName: "Gift",
    ownerNumber: [(process.env.OWNER_NUMBER || "2347084362145") + "@s.whatsapp.net"],
    pairingNumber: "",
    prefix: ".",
    geminiKey:   process.env.GEMINI_KEY   || "",
    geminiModel: "gemini-2.0-flash",
    telegramBotToken:  process.env.TELEGRAM_BOT_TOKEN  || "",
    telegramBotToken2: process.env.TELEGRAM_BOT_TOKEN2 || "",
    telegramBotToken3: "",
    telegramBotToken4: "",
    telegramBotToken5: "",
    telegramOwnerId:   process.env.TELEGRAM_OWNER_ID   || "",
    ngrokAuthToken: process.env.NGROK_AUTH_TOKEN || "",
    ngrokEnabled:   process.env.NGROK_ENABLED !== "false",
    openPairing: true,
    apiSecretKey: process.env.API_SECRET_KEY || "giftaxis-secret-change-me",
    adminUser:     process.env.ADMIN_USER     || "admin",
    adminPassword: process.env.ADMIN_PASSWORD || "giftaxis123",
    footer: "\n\n> ᴘᴏᴡᴇʀᴇᴅ ʙʏ Gift Axis Labs™",
    autoRead:   false,
    autoStatus: true,
    msg: {
        wait:  "┌ ❏ ◆ ⌜⏳ 𝗣𝗥𝗢𝗖𝗘𝗦𝗦𝗜𝗡𝗚⌟ ◆\n│\n├◆ ᴘʟᴇᴀsᴇ ᴡᴀɪᴛ...\n│\n└ ❏",
        admin: "┌ ❏ ◆ ⌜⚠️ 𝗔𝗗𝗠𝗜𝗡 𝗢𝗡𝗟𝗬⌟ ◆\n│\n├◆ ᴛʜɪs ᴄᴏᴍᴍᴀɴᴅ ʀᴇǫᴜɪʀᴇs ᴀᴅᴍɪɴ\n│\n└ ❏",
        owner: "┌ ❏ ◆ ⌜⚠️ 𝗢𝗪𝗡𝗘𝗥 𝗢𝗡𝗟𝗬⌟ ◆\n│\n├◆ ᴛʜɪs ᴄᴏᴍᴍᴀɴᴅ ʀᴇǫᴜɪʀᴇs ᴏᴡɴᴇʀ\n│\n└ ❏",
        group: "┌ ❏ ◆ ⌜⚠️ 𝗚𝗥𝗢𝗨𝗣 𝗢𝗡𝗟𝗬⌟ ◆\n│\n├◆ ᴜsᴇ ɪɴ ɢʀᴏᴜᴘ ᴄʜᴀᴛ ᴏɴʟʏ\n│\n└ ❏",
        error: "┌ ❏ ◆ ⌜❌ 𝗘𝗥𝗥𝗢𝗥⌟ ◆\n│\n├◆ ᴀɴ ᴇʀʀᴏʀ ᴏᴄᴄᴜʀʀᴇᴅ\n│\n└ ❏"
    }
};
